# Generated by Django 4.0.4 on 2022-06-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C1',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=50)),
                ('curcive_text', models.CharField(max_length=50)),
                ('bold_text', models.CharField(max_length=50)),
                ('big_bold_text', models.CharField(max_length=50)),
                ('since_date', models.CharField(max_length=50)),
                ('carousal_link', models.CharField(max_length=50)),
                ('carousal_image', models.ImageField(default='', upload_to='ecomsite/images')),
            ],
        ),
        migrations.CreateModel(
            name='choose_us',
            fields=[
                ('choose_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=50)),
                ('card_image', models.ImageField(default='', upload_to='ecomsite/images')),
                ('card_tite_1', models.CharField(default='', max_length=50)),
                ('card_tite_2', models.CharField(default='', max_length=50)),
                ('card_content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='fleet',
            fields=[
                ('fleet_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('para_1', models.TextField(default='')),
                ('para_2', models.TextField(default='')),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mng',
            fields=[
                ('mng_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('icon_1', models.ImageField(default='', upload_to='ecomsite/images')),
                ('icon_2', models.ImageField(default='', upload_to='ecomsite/images')),
                ('icon_3', models.ImageField(default='', upload_to='ecomsite/images')),
                ('image', models.ImageField(default='', upload_to='ecomsite/images')),
            ],
        ),
        migrations.CreateModel(
            name='our_story',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('story_name', models.CharField(max_length=50)),
                ('story_title', models.CharField(max_length=50)),
                ('bold_title', models.CharField(max_length=50)),
                ('para1', models.TextField(default='')),
                ('para2', models.TextField(default='')),
                ('btn_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='prod_home',
            fields=[
                ('prod_home_id', models.AutoField(primary_key=True, serialize=False)),
                ('home_prod_img', models.ImageField(default='', upload_to='ecomsite/images')),
                ('home_prod_title', models.CharField(max_length=50)),
                ('home_prod_desc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('confpasswd', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('streetadd', models.TextField(default='')),
                ('city', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
                ('provunce', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('shipsa', models.TextField(default='')),
                ('shipcity', models.CharField(max_length=50)),
                ('shippostalode', models.CharField(max_length=50)),
                ('shipprovince', models.CharField(max_length=50)),
                ('shipcountry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='ecomsite/images')),
                ('title', models.CharField(max_length=50)),
                ('para_1', models.TextField(default='')),
                ('para_2', models.TextField(default='')),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sold_prod',
            fields=[
                ('sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('curcive_text', models.CharField(max_length=50)),
                ('text_1', models.CharField(max_length=50)),
                ('text_2', models.CharField(max_length=50)),
                ('sub_text', models.CharField(max_length=50)),
                ('sp_image', models.ImageField(default='', upload_to='ecomsite/images')),
            ],
        ),
        migrations.CreateModel(
            name='supp',
            fields=[
                ('supp_id', models.AutoField(primary_key=True, serialize=False)),
                ('supp_name', models.CharField(max_length=50)),
                ('supp_image', models.ImageField(default='', upload_to='ecomsite/images')),
            ],
        ),
        migrations.CreateModel(
            name='ww',
            fields=[
                ('ww_id', models.AutoField(primary_key=True, serialize=False)),
                ('ww_name', models.CharField(max_length=50)),
                ('ww_image', models.ImageField(default='', upload_to='ecomsite/images')),
            ],
        ),
    ]
