# Generated by Django 4.0.4 on 2022-06-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodlist',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_image', models.ImageField(default='', upload_to='ecomsite/images')),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_desc', models.TextField(default='')),
                ('prod_catagory', models.CharField(default='', max_length=50)),
                ('prod_Brand', models.CharField(default='', max_length=50)),
                ('prod_Supplier', models.CharField(default='', max_length=50)),
                ('Flash_Sale', models.BooleanField(default=False)),
                ('Seasonal_Promotion', models.BooleanField(default=False)),
            ],
        ),
    ]
