# Generated by Django 4.0.4 on 2022-06-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0002_prodlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodlist',
            name='Show_on_Dekstop',
            field=models.BooleanField(default=False),
        ),
    ]
