# Generated by Django 4.0.4 on 2022-06-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0003_prodlist_show_on_dekstop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prod_home',
        ),
    ]
