# Generated by Django 4.0.4 on 2022-06-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0005_prodlist_prod_details_prodlist_prod_price_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_of_brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=50)),
            ],
        ),
    ]
