# Generated by Django 4.0.4 on 2022-06-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0007_prodlist_prod_bran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodlist',
            name='prod_Brand',
        ),
    ]
