# Generated by Django 4.0.4 on 2022-06-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0010_prodlist_prod_cat_prodlist_prod_supp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodlist',
            name='prod_Supplier',
        ),
        migrations.RemoveField(
            model_name='prodlist',
            name='prod_catagory',
        ),
    ]
