# Generated by Django 4.0.4 on 2022-06-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0011_remove_prodlist_prod_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='passwd',
            field=models.CharField(max_length=255),
        ),
    ]
