# Generated by Django 4.0.4 on 2022-07-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0013_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
